name: Publish Docs

on:
  push:
    branches:
      - main    

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install DocFX tool globally
        run: dotnet tool install -g docfx

      - name: Clean _site folder before build
        run: rm -rf docfx_project/_site

      - name: Wait for cleanup to complete
        run: sleep 5

      - name: Build Documentation
        working-directory: docfx_project
        run: docfx build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docfx_project/_site
