name: Publish Coverage Report

on:
  push:
    branches:
      - main

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Bank/Bank.sln

      - name: Build solution
        run: dotnet build Bank/Bank.sln --no-restore --configuration Release

      - name: Run tests with coverage
        run: |
          dotnet test Bank/Bank.Domain.Tests/Bank.Domain.Tests.csproj \
            --no-build --configuration Release \
            --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator tool globally
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate coverage report (HTML)
        run: |
          reportgenerator \
            -reports:"Bank/Bank.Domain.Tests/TestResults/**/coverage.cobertura.xml" \
            -targetdir:"Bank/Bank.Domain.Tests/TestResults/CoverageReport" \
            -reporttypes:Html

      - name: Publish coverage report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Bank/Bank.Domain.Tests/TestResults/CoverageReport
          force_orphan: true

      - name: Build test project for mutation testing
        working-directory: Bank/Bank.Domain.Tests
        run: dotnet build --configuration Release

      - name: Install Stryker.NET tool globally
        run: |
          dotnet tool install -g dotnet-stryker
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run Stryker mutation testing
        working-directory: Bank/Bank.Domain.Tests
        run: dotnet-stryker
